version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "80:8080"
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - frontend
            - backend

    frontend:
        build:
            context: frontend/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./frontend:/frontend

    backend:
        build:
            context: backend/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./backend:/backend
        depends_on:
            - backend-php-fpm

    backend-php-fpm:
        build:
            context: backend/docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
        volumes:
            - ./backend:/backend

    backend-php-cli:
        build:
            context: backend/docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
        volumes:
            - ./backend:/backend

    backend-mariadb:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: lists
            MYSQL_DATABASE: lists
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mariadb: